use anyhow::Result;
use candle_core::{Device, Tensor};
use candle_nn::{Activation, Module, ops::softmax};

#[test]
fn test_tensors() -> anyhow::Result<()> {
    let a = Tensor::new(&[[1., 2.], [3., 4.], [4., 6.]], &Device::Cpu)?;
    let b = Tensor::new(&[[5., 6., 7.], [7., 8., 1.]], &Device::Cpu)?;
    let c = Tensor::new(100., &Device::Cpu)?;

    let g: Vec<Vec<f64>> = a.to_vec2()?;
    println!("{}", c.to_scalar::<f64>()?);
    println!("{g:?}");
    println!("{:?}", a.shape()); // Shape: [length, dimension depth]

    let s = a.reshape((6, 1))?;
    println!("s: {s:?}");

    let c = a.matmul(&b)?;
    let d = c.transpose(0, 1)?; // Swap axis 0 with 1
    let e = c.unsqueeze(0)?; // Operate on axis 0(outermost: x in shape: [x,y,...]) -> if x = 1,
    // remove it
    let f = e.squeeze(0)?; // c.squeeze(0) works same bcoz axis 0 for c isn't of size: 1 -- squeeze
    // only works if size of target axis = 1
    let g = c.narrow(1, 1, 2)?;
    let h = c.affine(2.0, 0.0)?; // affine(&self, scale, bias) ->  self * scale + bias

    println!(
        "c: {0:?}\nd: {1:?}\ne: {2:?}\nf: {3:?}\ng: {4:?}\nh: {5:?}",
        c.to_vec2::<f64>()?,
        d.to_vec2::<f64>()?,
        e.to_vec3::<f64>()?,
        f.to_vec2::<f64>()?,
        g.to_vec2::<f64>()?,
        h.to_vec2::<f64>()?,
    );

    Ok(())
}

// Simplied linear operations on models -- Y = XW + B
// Output = input * weight + bias
#[test]
fn linear_operations() -> anyhow::Result<()> {
    let x = Tensor::new(&[[1., 3.], [2., 5.]], &Device::Cpu)?; // Replicate a [2,2] input
    let w = Tensor::new(&[[2., 3., 1.], [5., 1., 9.]], &Device::Cpu)?; // Replicate a [2, 3] weight
    let b = Tensor::new(&[4., 11., 16.3], &Device::Cpu)?; // The bias of the operation

    let final_output = x.matmul(&w)?.broadcast_add(&b)?;
    println!("X: {:?} | Sh: {:?}", x.to_vec2::<f64>()?, x.shape());
    println!("W: {:?} | Sh: {:?}", w.to_vec2::<f64>()?, w.shape());
    println!("B: {:?} | Sh: {:?}", b.to_vec1::<f64>()?, b.shape());
    println!(
        "final: {:?} | Sh: {:?}",
        final_output.to_vec2::<f64>()?,
        final_output.shape()
    );
    Ok(())
}

// Simplified relu logic
#[test]
fn activation_relu() -> Result<()> {
    let tensor = Tensor::new(&[100., 3., -1., -54., -11.7], &Device::Cpu)?;

    // simple relu operations on tensor
    let mut inner_data = tensor.to_vec1::<f64>()?;
    for data in inner_data.iter_mut() {
        *data = data.max(0.);
    }
    let new_tensor = Tensor::new(&*inner_data, &Device::Cpu)?;
    println!("{:?}", new_tensor.to_vec1::<f64>()?);

    Ok(())
}

/// Simplified embedding logic
#[test]
fn embedding_lookup() -> Result<()> {
    // Tokens generated by tokenizer are converted to embeddings
    // Set of testing embeddings to be tried out for testing
    let embeddings = Tensor::new(
        &[
            [0.2, 0.5, 0.1], // cat
            [0.8, 0.4, 0.9], // dog
            [0.1, 0.7, 0.3], // fish
            [0.9, 0.2, 0.8], // Rust
            [0.5, 0.6, 0.4], // AI
        ],
        &Device::Cpu,
    )?;

    let tokens = Tensor::new(&[3u32, 4], &Device::Cpu)?;
    let final_tensor = embeddings.index_select(&tokens, 0)?;

    println!("{:?}", final_tensor.to_vec2::<f64>()?);

    Ok(())
}

// To test out old-model positional embedding architecture(direct matrices addition), not RoPE
#[test]
fn positional_embeddings() -> Result<()> {
    // Mock token vectors used for demonstration purposes
    let token_embeddings = Tensor::new(
        &[
            [0.2, 0.8, 0.1, 0.5], // Rust
            [0.7, 0.3, 0.9, 0.2], // is
            [0.4, 0.5, 0.6, 0.8], // awesome
        ],
        &Device::Cpu,
    )?;

    // Simple positional embeddings
    // Row i corresponds to position i in the sequence.
    let position_embeddings = Tensor::new(
        &[
            [0.01, 0.02, 0.03, 0.04], // Position 0 -- Rust
            [0.05, 0.06, 0.07, 0.08], // Position 1 -- is
            [0.09, 0.10, 0.11, 0.12], // Position 2 -- awesome
        ],
        &Device::Cpu,
    )?;

    let input = (&token_embeddings + &position_embeddings)?;

    println!("T: {:?}", token_embeddings.to_vec2::<f64>()?);
    println!("P: {:?}", position_embeddings.to_vec2::<f64>()?);
    println!("I: {:?}", input.to_vec2::<f64>()?);

    Ok(())
}

#[test]
fn query_key_value() -> Result<()> {
    // Mock input vector from tokens
    let x = Tensor::new(&[[1., 2.], [3., 4.]], &Device::Cpu)?;

    // Mock query, key, value weight embeddings
    let wq = Tensor::new(&[[1.1, 4.1], [0.4, 6.2]], &Device::Cpu)?;
    let wk = Tensor::new(&[[0.5, 2.1], [1.6, 2.2]], &Device::Cpu)?;
    let wv = Tensor::new(&[[1.8, 9.1], [0.3, 7.8]], &Device::Cpu)?;

    // Multiply with the weight vectors to get the different vectors of:
    // Query, Key, Value
    #[allow(non_snake_case)]
    {
        // Different linear projections on the input vector based on different weight vectors
        let Q = x.matmul(&wq)?;
        let K = x.matmul(&wk)?;
        let V = x.matmul(&wv)?;

        println!("{:?}", Q.to_vec2::<f64>()?);
        println!("{:?}", K.to_vec2::<f64>()?);
        println!("{:?}", V.to_vec2::<f64>()?);
    }

    Ok(())
}

// NOTE: The following metrics used for attention scores are fairly large, doesn't happen irl --
// used to track the variation of attention weights based on attention scores

// Mock demonstration of attention scores calculation
fn attention_scores() -> Result<(Tensor, Tensor, Tensor)> {
    // Mock input -- each inner array is an embedded data of an input token
    let x = Tensor::new(&[[1., 2.], [3., 4.]], &Device::Cpu)?;

    // Mock weights of query and key
    let wq = Tensor::new(&[[5., 6.], [2., 1.]], &Device::Cpu)?;
    let wk = Tensor::new(&[[1.3, 3.2], [5.21, 9.33]], &Device::Cpu)?;

    // Get the query and key
    let q = x.matmul(&wq)?;
    let k = x.matmul(&wk)?;
    // Attention Scores(A) = Q*K(transpose) -- transpose to convert the dimensions to allow
    // multiplication(no change in data)
    let attention_scores = q.matmul(&k.transpose(0, 1)?)?;

    println!("Q: {:?}", q.to_vec2::<f64>()?);
    println!("K: {:?}", k.to_vec2::<f64>()?);
    println!("A: {:?}", attention_scores.to_vec2::<f64>()?);

    Ok((x, q, attention_scores))
}

// Apply softmaxing on attention scores
#[test]
fn softmaxed_attention_scores() -> Result<()> {
    let (x, q, scores) = attention_scores()?;
    let dk = q.dims2()?.1 as f64; // Get the no. of embeddings' per token value
    // Scale attention scores by 1/sqrt(d_k) to keep their magnitude
    // stable before softmax and avoid softmax saturation during training.
    let scaled_scores = scores.affine(1.0 / dk.sqrt(), 0.0)?;
    println!("Scaled Scores: {:?}", scaled_scores.to_vec2::<f64>()?);

    // Softmaxxed scores
    let softmaxed = softmax(&scaled_scores, 1)?; // sofmax the target on dim 1(inner rows independently)
    // Mock weight matrix for values(independent on x)
    let wv = Tensor::new(&[[4., 13.], [11.2, 4.6]], &Device::Cpu)?;

    let v = x.matmul(&wv)?; // Final version of attention weights
    let av = softmaxed.matmul(&v)?; // Final value matrix produced

    println!("Softmax: {:?}", softmaxed.to_vec2::<f64>()?);
    println!("WV: {:?}", wv.to_vec2::<f64>()?);
    println!("V: {:?}", v.to_vec2::<f64>()?);
    println!("AV: {:?}", av.to_vec2::<f64>()?);

    Ok(())
}

// Implement FFN with GeLU
#[test]
fn ffn_with_gelu() -> Result<()> {
    // Mock input and first ffn weight to convert to higher dimensional embedding per token
    let x = Tensor::new(&[[1., 4.], [0.2, 0.4]], &Device::Cpu)?;
    let w1 = Tensor::new(&[[0.5, 0.3, 0.2, 0.8], [0.1, 0.7, 0.9, 0.4]], &Device::Cpu)?;
    let expanded = x.matmul(&w1)?; // The expanded format -- fed to GeLU

    let activated = Activation::Gelu.forward(&expanded)?;
    let w2 = Tensor::new(
        &[[0.4, 0.8], [0.2, 0.1], [0.9, 0.5], [0.3, 0.7]],
        &Device::Cpu,
    )?; // Final mock ffn weight to convert back to original token embedding dimensions
    let output = activated.matmul(&w2)?;

    println!("Input: {:?}", x.to_vec2::<f64>()?);
    println!("Expanded: {:?}", expanded.to_vec2::<f64>()?);
    println!("Activated: {:?}", activated.to_vec2::<f64>()?);
    println!("Output: {:?}", output.to_vec2::<f64>()?);
    println!("Gelu Output: {:?}", output.to_vec2::<f64>()?);

    Ok(())
}

// Implement a residual addition over the FFN output
#[test]
fn residual_connection() -> Result<()> {
    let x = Tensor::new(&[[1., 2.], [3., 4.]], &Device::Cpu)?; // Mock input(FFN Output)
    // Final attention score -- after complete computation(matmul with value weight matrix)
    let attention_score = Tensor::new(&[[0.5, -0.2], [0.1, 0.8]], &Device::Cpu)?;
    let residual = (&x + &attention_score)?;

    println!("Input: {:?}", x.to_vec2::<f64>()?);
    println!("Block: {:?}", attention_score.to_vec2::<f64>()?);
    println!("Residual: {:?}", residual.to_vec2::<f64>()?);

    Ok(())
}
