use std::{mem::MaybeUninit, sync::OnceLock};

use anyhow::Result;
use candle_core::{Device, Tensor};
use candle_nn::{Activation, Module, ops::softmax};

#[test]
fn test_tensors() -> anyhow::Result<()> {
    let a = Tensor::new(&[[1., 2.], [3., 4.], [4., 6.]], &Device::Cpu)?;
    let b = Tensor::new(&[[5., 6., 7.], [7., 8., 1.]], &Device::Cpu)?;
    let c = Tensor::new(100., &Device::Cpu)?;

    let g: Vec<Vec<f64>> = a.to_vec2()?;
    println!("{}", c.to_scalar::<f64>()?);
    println!("{g:?}");
    println!("{:?}", a.shape()); // Shape: [length, dimension depth]

    let s = a.reshape((6, 1))?;
    println!("s: {s:?}");

    let c = a.matmul(&b)?;
    let d = c.transpose(0, 1)?; // Swap axis 0 with 1
    let e = c.unsqueeze(0)?; // Operate on axis 0(outermost: x in shape: [x,y,...]) -> if x = 1,
    // remove it
    let f = e.squeeze(0)?; // c.squeeze(0) works same bcoz axis 0 for c isn't of size: 1 -- squeeze
    // only works if size of target axis = 1
    let g = c.narrow(1, 1, 2)?;
    let h = c.affine(2.0, 0.0)?; // affine(&self, scale, bias) ->  self * scale + bias

    println!(
        "c: {0:?}\nd: {1:?}\ne: {2:?}\nf: {3:?}\ng: {4:?}\nh: {5:?}",
        c.to_vec2::<f64>()?,
        d.to_vec2::<f64>()?,
        e.to_vec3::<f64>()?,
        f.to_vec2::<f64>()?,
        g.to_vec2::<f64>()?,
        h.to_vec2::<f64>()?,
    );

    Ok(())
}

// Simplied linear operations on models -- Y = XW + B
// Output = input * weight + bias
#[test]
fn linear_operations() -> anyhow::Result<()> {
    let x = Tensor::new(&[[1., 3.], [2., 5.]], &Device::Cpu)?; // Replicate a [2,2] input
    let w = Tensor::new(&[[2., 3., 1.], [5., 1., 9.]], &Device::Cpu)?; // Replicate a [2, 3] weight
    let b = Tensor::new(&[4., 11., 16.3], &Device::Cpu)?; // The bias of the operation

    let final_output = x.matmul(&w)?.broadcast_add(&b)?;
    println!("X: {:?} | Sh: {:?}", x.to_vec2::<f64>()?, x.shape());
    println!("W: {:?} | Sh: {:?}", w.to_vec2::<f64>()?, w.shape());
    println!("B: {:?} | Sh: {:?}", b.to_vec1::<f64>()?, b.shape());
    println!(
        "final: {:?} | Sh: {:?}",
        final_output.to_vec2::<f64>()?,
        final_output.shape()
    );
    Ok(())
}

// Simplified relu logic
#[test]
fn activation_relu() -> Result<()> {
    let tensor = Tensor::new(&[100., 3., -1., -54., -11.7], &Device::Cpu)?;

    // simple relu operations on tensor
    let mut inner_data = tensor.to_vec1::<f64>()?;
    for data in inner_data.iter_mut() {
        *data = data.max(0.);
    }
    let new_tensor = Tensor::new(&*inner_data, &Device::Cpu)?;
    println!("{:?}", new_tensor.to_vec1::<f64>()?);

    Ok(())
}

/// Simplified embedding logic
#[test]
fn embedding_lookup() -> Result<()> {
    // Tokens generated by tokenizer are converted to embeddings
    // Set of testing embeddings to be tried out for testing
    let embeddings = Tensor::new(
        &[
            [0.2, 0.5, 0.1], // cat
            [0.8, 0.4, 0.9], // dog
            [0.1, 0.7, 0.3], // fish
            [0.9, 0.2, 0.8], // Rust
            [0.5, 0.6, 0.4], // AI
        ],
        &Device::Cpu,
    )?;

    let tokens = Tensor::new(&[3u32, 4], &Device::Cpu)?;
    let final_tensor = embeddings.index_select(&tokens, 0)?;

    println!("{:?}", final_tensor.to_vec2::<f64>()?);

    Ok(())
}

// To test out old-model positional embedding architecture(direct matrices addition), not RoPE
#[test]
fn positional_embeddings() -> Result<()> {
    // Mock token vectors used for demonstration purposes
    let token_embeddings = Tensor::new(
        &[
            [0.2, 0.8, 0.1, 0.5], // Rust
            [0.7, 0.3, 0.9, 0.2], // is
            [0.4, 0.5, 0.6, 0.8], // awesome
        ],
        &Device::Cpu,
    )?;

    // Simple positional embeddings
    // Row i corresponds to position i in the sequence.
    let position_embeddings = Tensor::new(
        &[
            [0.01, 0.02, 0.03, 0.04], // Position 0 -- Rust
            [0.05, 0.06, 0.07, 0.08], // Position 1 -- is
            [0.09, 0.10, 0.11, 0.12], // Position 2 -- awesome
        ],
        &Device::Cpu,
    )?;

    let input = (&token_embeddings + &position_embeddings)?;

    println!("T: {:?}", token_embeddings.to_vec2::<f64>()?);
    println!("P: {:?}", position_embeddings.to_vec2::<f64>()?);
    println!("I: {:?}", input.to_vec2::<f64>()?);

    Ok(())
}

#[test]
fn query_key_value() -> Result<()> {
    // Mock input vector from tokens
    let x = Tensor::new(&[[1., 2.], [3., 4.]], &Device::Cpu)?;

    // Mock query, key, value weight embeddings
    let wq = Tensor::new(&[[1.1, 4.1], [0.4, 6.2]], &Device::Cpu)?;
    let wk = Tensor::new(&[[0.5, 2.1], [1.6, 2.2]], &Device::Cpu)?;
    let wv = Tensor::new(&[[1.8, 9.1], [0.3, 7.8]], &Device::Cpu)?;

    // Multiply with the weight vectors to get the different vectors of:
    // Query, Key, Value
    #[allow(non_snake_case)]
    {
        // Different linear projections on the input vector based on different weight vectors
        let Q = x.matmul(&wq)?;
        let K = x.matmul(&wk)?;
        let V = x.matmul(&wv)?;

        println!("{:?}", Q.to_vec2::<f64>()?);
        println!("{:?}", K.to_vec2::<f64>()?);
        println!("{:?}", V.to_vec2::<f64>()?);
    }

    Ok(())
}

// ====== Contributing to building the transformer block =====================

const N_HEADS: usize = 2; // No of heads for self-attention

struct AttentionHead {
    wq: Tensor, // Weight of queries
    wk: Tensor, // Weight of keys
    wv: Tensor, // Weight of value
}

struct TransformerBlock {
    // SELF-ATTENTION
    heads: [AttentionHead; N_HEADS], // The heads used for computation
    wo: Tensor,                      // Final projection weight

    // FFN
    ffn1: Tensor, // Expander weight to perform ffn
    ffn2: Tensor, // Compressor weight after computation from expanded form

    // Layer normalization -- used metrics
    beta: Vec<f64>,
    gamma: Vec<f64>,
}
const EMBEDDINGS_PER_TOKEN: usize = 2; // No of embedding features per token
const EPS: f64 = 1e-5; // EPS used during normaliztion
static TRANSFORMER: OnceLock<TransformerBlock> = OnceLock::new();

// Helper MACRO to refer to the global transformer block
macro_rules! TRANS {
    () => {
        TRANSFORMER.get().unwrap()
    };
}

// NOTE: The following metrics used for attention scores are fairly large, doesn't happen irl --
// used to track the variation of attention weights based on attention scores
// Mock demonstration of attention scores calculation
fn self_attention(x: &Tensor) -> Result<Tensor> {
    // Stores the tensors containing attention value per head
    let mut attention_values: Vec<Tensor> = Vec::with_capacity(N_HEADS);

    for (idx, head) in TRANS!().heads.iter().enumerate() {
        // Get the query and key
        let q = x.matmul(&head.wq)?;
        let k = x.matmul(&head.wk)?;

        // Attention Scores(A) = Q*K(transpose) -- transpose to convert the dimensions to allow
        // multiplication(no change in data)
        let attention_score = q.matmul(&k.transpose(0, 1)?)?;

        println!("[ATTENTION HEAD]: {} Q: {:?}", idx, q.to_vec2::<f64>()?);
        println!("[ATTENTION HEAD]: {} K: {:?}", idx, k.to_vec2::<f64>()?);
        println!(
            "[ATTENTION HEAD]: {} A: {:?}",
            idx,
            attention_score.to_vec2::<f64>()?
        );

        // Scale attention scores by 1/sqrt(d_k) to keep their magnitude
        // stable before softmax and avoid softmax saturation during training.
        let scaled_score =
            attention_score.affine(1.0 / ((EMBEDDINGS_PER_TOKEN / N_HEADS) as f64).sqrt(), 0.0)?;
        println!(
            "[ATTENTION HEAD]: {} Scaled Scores: {:?}",
            idx,
            scaled_score.to_vec2::<f64>()?
        );

        // Softmaxxed scores
        let softmaxed = softmax(&scaled_score, 1)?; // sofmax the target on dim 1(inner rows independently)
        let v = x.matmul(&head.wv)?; // Final version of attention weights
        let attention_output = softmaxed.matmul(&v)?; // Final value matrix produced

        println!(
            "[ATTENTION HEAD]: {} Softmax: {:?}",
            idx,
            softmaxed.to_vec2::<f64>()?
        );
        println!(
            "[ATTENTION HEAD]: {} WV: {:?}",
            idx,
            head.wv.to_vec2::<f64>()?
        );
        println!("[ATTENTION HEAD]: {} V: {:?}", idx, v.to_vec2::<f64>()?);
        println!(
            "[ATTENTION HEAD]: {} AV: {:?}",
            idx,
            attention_output.to_vec2::<f64>()?
        );

        attention_values.push(attention_output);
    }

    let combined_attention_output = Tensor::cat(&attention_values, 1)?;
    let projected = combined_attention_output.matmul(&TRANS!().wo)?;
    println!(
        "[ATTENTION] Final Projection: {:?}",
        projected.to_vec2::<f64>()?
    );

    Ok(projected)
}

// Implement FFN with GeLU
fn ffn_with_gelu(x: &Tensor) -> Result<Tensor> {
    // Mock input and first ffn weight to convert to higher dimensional embedding per token
    let expanded = x.matmul(&TRANS!().ffn1)?; // The expanded format -- fed to GeLU

    let activated = Activation::Gelu.forward(&expanded)?;
    let output = activated.matmul(&TRANS!().ffn2)?;

    println!("[FFN_WITH_GELU] Final Input: {:?}", x.to_vec2::<f64>()?);
    println!("[FFN_WITH_GELU] Expanded: {:?}", expanded.to_vec2::<f64>()?);
    println!(
        "[FFN_WITH_GELU] Activated: {:?}",
        activated.to_vec2::<f64>()?
    );
    println!("[FFN_WITH_GELU] Output: {:?}", output.to_vec2::<f64>()?);
    println!(
        "[FFN_WITH_GELU] Gelu Output: {:?}",
        output.to_vec2::<f64>()?
    );

    Ok(output)
}

// Implement a residual addition over the FFN output
fn residual_addition(x: &mut Tensor, second_mat: &Tensor) -> Result<()> {
    *x = (&*x + second_mat)?;

    println!("[RESIDUE] Input after Addition: {:?}", x.to_vec2::<f64>()?);
    Ok(())
}

// Implement layer norm on a provided tensor
fn create_layer_norm(inp: &Tensor) -> Result<Tensor> {
    // Extract the data from the input tensor
    let mut inner_data = inp.to_vec2::<f64>()?;
    let rows = inner_data.len();

    // Iter over all the props per token's embedding
    for embeddings in inner_data.iter_mut() {
        // Get the average
        let avg = embeddings.iter().sum::<f64>() / EMBEDDINGS_PER_TOKEN as f64;

        // Get the variance
        let variance = embeddings.iter().map(|x| (*x - avg).powi(2)).sum::<f64>()
            / EMBEDDINGS_PER_TOKEN as f64;
        let denom = (EPS + variance).sqrt();

        // Normalize each element
        for (idx, embed) in embeddings.iter_mut().enumerate() {
            *embed = TRANS!().gamma[idx] * (*embed - avg) / denom + TRANS!().beta[idx];
        }
    }

    // Inner data is Vec<Vec<f64>> -- it can't be made into a Tensor in this format because Tensor
    // accepts: [[f64; N]; M] -- but the internal vec cannot be extracted
    // So, flat out the memory layout(doesn't change it) -- then convert it in tensor creation
    let inner_data = inner_data.into_iter().flatten().collect();
    Ok(Tensor::from_vec(
        inner_data,
        (rows, EMBEDDINGS_PER_TOKEN),
        &Device::Cpu,
    )?)
}

// Mimics a simplified calculation of a transformer
#[test]
fn create_transformer_block() -> Result<()> {
    let mut blank_data = [const { MaybeUninit::<AttentionHead>::uninit() }; N_HEADS];
    for idx in 0..N_HEADS {
        blank_data[idx].write(AttentionHead {
            wq: Tensor::new(&[[5.], [2.]], &Device::Cpu).unwrap(),
            wk: Tensor::new(&[[1.3], [5.21]], &Device::Cpu).unwrap(),
            wv: Tensor::new(&[[4.], [11.2]], &Device::Cpu).unwrap(),
        });
    }
    // All memory blocks are updated, treat it as a stable type now
    let heads: [AttentionHead; N_HEADS] = unsafe { std::mem::transmute(blank_data) };

    _ = TRANSFORMER.set(TransformerBlock {
        heads,
        wo: Tensor::new(&[[0.3, 0.8], [0.6, 0.1]], &Device::Cpu)?,
        ffn1: Tensor::new(&[[0.5, 0.3, 0.2, 0.8], [0.1, 0.7, 0.9, 0.4]], &Device::Cpu)?,
        ffn2: Tensor::new(
            &[[0.4, 0.8], [0.2, 0.1], [0.9, 0.5], [0.3, 0.7]],
            &Device::Cpu,
        )?,
        beta: vec![0.23; EMBEDDINGS_PER_TOKEN],
        gamma: vec![0.49; EMBEDDINGS_PER_TOKEN],
    });

    let x = Tensor::new(&[[1., 2.], [3., 4.]], &Device::Cpu)?;
    let mut x = create_layer_norm(&x)?; // Create the normalized tensor
    let attention = self_attention(&x)?; // Get the (query, attention scores)
    residual_addition(&mut x, &attention)?; // Get the residual addition result

    let mut x = create_layer_norm(&x)?; // Create a new layer normalization result
    let ffn_output = ffn_with_gelu(&x)?; // Apply ffn with gelu over the new input
    residual_addition(&mut x, &ffn_output)?; // Add the residue over the ffn result

    Ok(())
}
